#!/usr/bin/env php
<?php
require __DIR__ . DIRECTORY_SEPARATOR . 'main.php';

const DESKTOP_PATH = 'C:\\Users\\Administrator\\Desktop\\';

$app->shell->setScopeVariables([
    'app' => $app,
    'DESKTOP_PATH' => DESKTOP_PATH,
    'APP_PATH' => APP_PATH,
    'VIEW_PATH' => VIEW_PATH,
    'ENV_PATH' => ENV_PATH
]);

$app->shell->run();
