#!/usr/bin/env php
<?php
require __DIR__ . DIRECTORY_SEPARATOR . 'main.php';

const DESKTOP_PATH = 'C:\\Users\\Administrator\\Desktop\\';

$app->shell->setScopeVariables([
    'app' => $app,
]);

$app->shell->run();
